rvm:
- 2.5.0
script:
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: 24l9oz07QNoMrI4Z+EsNUF4YxDM73yElT5aIpjcs1lQyJWOX9FEMiq241sVFIAFKiicu03IMwoLHhEktUn/CJoTMdn+k8cYMNVh2ZfjXX2d3urK/YaswWCzfIDAYOrLPGcYIjxTRzaiFYuHudhEb7x9Obn2JdhOGPMFpOcNY7/p7Op1GPnL1M5sdaZ7nMAz2vBNuujMGAqotDKcSMlk7OWrg3BTgLFcR+7gcHh4PUKiGG/EahjXeSxqFMWvH+76O1wjZRA4igUnlB3tfkJpLspLJDOeJzi2q6M7J2oBAyUSRUX6iqr3jMwv+kE1Ts0CWIPzDlxNQibItSl9FWVgOBQWH8iSPOB9BKrZ6VhIlSdf8JGpLQ2vjq/MFOguXRdgONpSDTS/IOdcwiQ2Hupu9ZVLNmy2j5kYlIBvS4wvnuaBuCCnRv2igrtkB56z2wkJ4NnjA1H2whTFKZbWwreWXoKWT1Rl4XqNqRQBRJAnP+gcJJ1m37gByBnX6r96gaJdotyXnqctljMO4tX51Qfk5W3L86TJ5dYpZ6jE60bOT3HRtq6POOy/PO6a+yv5DVcda98W2C/eDSXKDjypFaNfScndfSVFIcEMJR3/6ohcivqCUjMaSYn0oD33scUD2CjnkAFiNgxgYBaw9H6Xx1Vi8sUiuR7gU1P4JfPotAYV7IT0=
