rvm:
- 2.5.0
script:
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: d6L10uQtkRevasykFB0VvSGPAf7wf8gh9vAAAbFAJwACTHWLN8hKnuIY88Lm96XueSWWwTQKHxGQfflH05Hn2+POgIdmtKYZWQkaPyqXRDWSiGB00+wlpFeBf/OsnvWDhmHrKf2n1x60iV+UmatfKKQJeTlxCp7ObP/foOAoSBX6bk6aA2LU8M5p73aYeO31qKUqh985HoHWdC1MhNRAprUuHFz1L0USF3tlVTiT4N583NcjkWmwxUSUf8o6GSsdFOxDeD/oXb/EKWTQh+WTyLdGhcOuiH3wxOWdSdncxmySg35V64lzNWxSJiRJDvYmfAH0q+wbdQBQ2DGk3OCq0I3BRcJxKllidD/Uf/2RDJy5ZHyf2eaKo4Ba9R/5FUYbKKmZnRh4rcisBMYJ076v6BabKnlUe8ia0mOcXg6i2jOidEnVGOzU7UJwCWNDSfrlGIQ3m+VZYkcuT+WgR4AFe0Eyvojc+Vw2y0dm+oGG5+5QQwDDofOCE9ZTMVLxAan29Hy55jBMjSTAhJXz1NNwqPU9u2h7fPozCT/1MOiAFZUSMI3XMVumFQ90bexjczXZFj+xN0dO2LE9+TELM7AVOJor8+TqQl321ahIJL/QD4dr5kU9gRwgD8oMfyiiG0nem3cUvUi3fuz0CqJeXjHhbVSIjiugWxs0CHpYNMjMp5A=
