rvm:
- 2.5.0
script:
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: MCmuudt0SRfHVC9HrFoHGY/vHOMMYe2KBy5wKcIHr+dqhBEyVcyPGGMyVVAFNlL+rISFUsLalV79HlXDEOfGocjEsfkNSNXId8fg7OE7+n3YaPy86n392Isv6hh3WTM5hXXy4hSluyc0N62d3V8LRQ+ZKPlvNu+8w9gr83EHjdAzM15fFQQwIFXwYN+jyIjRkvKPeWQGn/QPVtlUUL8Go/suhjDp/XeL9il2/8IYAHduAphTV5fjsddQ7hqNFV2ocPBk/dtCOHmb/TN3Isb6XbHklHcHDI1V/V0TWdK3Ovto1xHJzi8tYfPwOedn6umIs2Yh2cCBnr4/aAfr9Pa+74Ktk9W6VCDUS6/Xd7cxLdTKvQ8FFNyjTYsBEyQhkC8MOdH4M2hNftpkOVxy4oJm90XTAUeR1YD/6T+FriIEot7dbZYxqdvh4VnZwPK1quGR/CyJDAXMceZHhR7/Kc7GogYwLXgNeZCkCS5vRB7Gz+yeO2mDhgh/+fqSjcx3XQ/aLN0zUZoNHOCLpd8rLfKwcSdX/uq1wtdGusZrO6JkpzQufj6vDj3Jo1ng1Pfqg/76iCquRtVfVP/5N5ljR8ILvbbboUQanDEOM3aGgNntIZAI9NbEhq9f2CR4CCSFMHOHtJ4IpUsrj3ppQH/X0a9mUyUiK6GnxCSZgJI5vDIhfag=
